log:
  level: INFO

accessLog: {}

api:
  insecure: true

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik.d"
    watch: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

serversTransport:
  insecureSkipVerify: true